<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.boot</groupId>
        <artifactId>boot-assembly</artifactId>
        <version>4.6.0</version>
    </parent>

    <artifactId>boot-mono</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-rbac-service</artifactId>
            <version>4.6.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.Tencent</groupId>
            <artifactId>APIJSON</artifactId>
            <version>7.1.0</version>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>com.github.APIJSON</groupId>-->
        <!--            <artifactId>apijson-framework</artifactId>-->
        <!--            <version>7.1.5</version>-->
        <!--            <exclusions>-->
        <!--                <exclusion>-->
        <!--                    <groupId>javax.servlet</groupId>-->
        <!--                    <artifactId>javax.servlet-api</artifactId>-->
        <!--                </exclusion>-->
        <!--            </exclusions>-->
        <!--        </dependency>-->

        <dependency>
            <groupId>org.ssssssss</groupId>
            <artifactId>magic-api-spring-boot-starter</artifactId>
            <version>2.2.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.ssssssss</groupId>
                    <artifactId>magic-api-servlet-javaee</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- AI应用
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-ai-service</artifactId>
            <version>4.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-core</artifactId>
            <version>1.0.0-M6</version>
        </dependency>
        -->

        <!-- 开发工具 -->
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-devtool-app</artifactId>
            <version>4.6.0</version>
        </dependency>

        <!-- 自身作为xxl-job节点
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-commons-xxl-job</artifactId>
        </dependency>
        -->
        <!-- 公众号 -->
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-mp-service</artifactId>
            <version>4.6.0</version>
        </dependency>

        <!-- 支付例子 -->
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-pay-service</artifactId>
            <version>4.6.0</version>
        </dependency>

        <!-- 日志服务  -->
        <dependency>
            <groupId>io.boot</groupId>
            <artifactId>boot-commons-log</artifactId>
        </dependency>

        <!-- springcloud 依赖-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
    </dependencies>

    <repositories>
        <!-- APIJSON 必须用到的托管平台 -->
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>


</project>