server:
  port: 8092
  servlet:
    context-path: /api-client

spring:
  application:
    name: api-client
  profiles:
    active: dev
  # 国际化
  messages:
    encoding: UTF-8
    basename: i18n/messages_api_client,i18n/messages_common
  # 校验错误国际化
  validations:
    basename:
      - i18n/validation_api_client
      - i18n/validation_common

# 客户端接入配置
api-client:
  client-id: 9999
  api-url: https://127.0.0.1:8091/api
  platform-key: '1111111'
  private-key: 'kkkk'