server:
  port: 8000
  servlet:
    context-path: /api-client

spring:
  application:
    name: api-client
  #环境 dev|test|prod
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages_api_client,i18n/messages_common
  validations:
    basename:
      - i18n/validation_api_client
      - i18n/validation_common

api-client:
  client-id: 9999
  api-url: https://127.0.0.1:9090/api
  # 平台公钥
  platform-key: '1111111'
  # 客户端私钥
  private-key: 'kkkk'